const sig = (label, type) => {
  const m = { intent: { bg: "#FAEEDA", color: "#854F0B" }, content: { bg: "#E6F1FB", color: "#185FA5" }, growth: { bg: "#E1F5EE", color: "#0F6E56" }, tech: { bg: "#EEEDFE", color: "#534AB7" }, risk: { bg: "#FCEBEB", color: "#A32D2D" }, momentum: { bg: "#E1F5EE", color: "#0F6E56" }, stakeholder: { bg: "#E6F1FB", color: "#185FA5" }, timing: { bg: "#FAEEDA", color: "#854F0B" }, competitive: { bg: "#EEEDFE", color: "#534AB7" }, coaching: { bg: "#FFF0E6", color: "#9C4D1A" } };
  return { label, ...(m[type] || m.intent) };
};

export const COMPANY_NAME = "Nasta Pet Food";
export const COMPANY_LOGO_LETTER = "N";
export const ROLE_LABEL = "Sales Manager";
export const REP = { name: "Elena Corsini", role: "Regional Sales Manager - North America" };

export const TABS = ["Hot prospects", "Retail expansion", "Follow-ups", "Team coaching"];

export const ALL_LEADS = {
  "Hot prospects": [
    { id: 1, name: "Mike Patterson", company: "Wag N' Wash", role: "Regional Buyer", stage: "Proposal", size: "$420K", score: 92, signals: [sig("Opening 12 new stores Q2", "growth"), sig("Requesting Forza10 samples", "intent"), sig("Premium nutrition focus", "content")], message: "Wag N' Wash opening 12 new franchise locations and actively sampling premium brands. Mike requested Forza10 Active Line samples last week. Follow up with clinical study data and propose an intro assortment of 18 SKUs.", priority: "high" },
    { id: 2, name: "Jessica Huang", company: "Pet Food Express", role: "Category Manager", stage: "Negotiation", size: "$380K", score: 89, signals: [sig("Competitor contract expiring May", "timing"), sig("Looking for Italian premium brands", "intent"), sig("Bay Area health-conscious market", "content")], message: "Pet Food Express dropping a competitor brand in May. Jessica specifically asked about Italian-made pet food with clinical backing. Natural Code and Forza10 are perfect fits for their health-conscious Bay Area customers.", priority: "high" },
    { id: 3, name: "Dr. Alan Reeves", company: "BluePearl Veterinary", role: "Purchasing Director", stage: "Proposal", size: "$310K", score: 87, signals: [sig("100+ specialty vet hospitals", "growth"), sig("Therapeutic diet expansion", "intent"), sig("Clinical evidence required", "content")], message: "BluePearl operates 100+ specialty hospitals and wants to expand therapeutic diet offerings. Dr. Reeves needs peer-reviewed clinical data. Send Forza10 Active Line studies on dermatological and GI formulas.", priority: "high" },
    { id: 4, name: "Tanya Brooks", company: "Loyal Companion", role: "VP Merchandising", stage: "Discovery", size: "$275K", score: 84, signals: [sig("Mid-Atlantic expansion", "growth"), sig("Premium wet food gap", "competitive"), sig("In-store nutrition advisor program", "content")], message: "Loyal Companion expanding across the Mid-Atlantic with 8 new stores. They have a gap in premium wet food. Natural Code's 85% meat content fits their nutrition advisor program perfectly.", priority: "high" },
    { id: 5, name: "Ryan O'Malley", company: "Mud Bay", role: "Buying Director", stage: "Qualification", size: "$245K", score: 81, signals: [sig("Pacific NW natural pet leader", "content"), sig("Sustainability sourcing priority", "content"), sig("Staff education program", "coaching")], message: "Mud Bay is the Pacific Northwest's top natural pet retailer. Ryan values ingredient transparency and staff education. Propose a Forza10 training program for their floor staff to drive recommendation rates.", priority: "medium" },
    { id: 6, name: "Sandra Levine", company: "Unleashed by Petco", role: "Small Format Buyer", stage: "Proposal", size: "$520K", score: 90, signals: [sig("Small-format premium focus", "intent"), sig("Neighborhood store expansion", "growth"), sig("Curated brand assortment", "competitive")], message: "Unleashed by Petco small-format stores curate only premium brands. Sandra wants 3-4 anchor brands per category. Our multi-brand portfolio (Forza10 + Natural Code) gives us a unique advantage here.", priority: "high" },
    { id: 7, name: "Kevin Tran", company: "Hollywood Feed", role: "Regional Manager", stage: "Negotiation", size: "$290K", score: 85, signals: [sig("Southeast expansion 15 stores", "growth"), sig("Staff-recommended brands only", "content"), sig("Demo event slots available", "timing")], message: "Hollywood Feed only sells staff-recommended brands across 90+ stores. Kevin offered in-store demo event slots in April. This is our chance to get Forza10 on their recommended list through hands-on staff experience.", priority: "high" },
    { id: 8, name: "Dr. Maria Santos", company: "VCA Animal Hospitals", role: "Nutrition Program Lead", stage: "Discovery", size: "$480K", score: 83, signals: [sig("1,000+ hospitals nationwide", "growth"), sig("Therapeutic diet formulary update", "intent"), sig("Mars subsidiary synergies", "stakeholder")], message: "VCA updating their therapeutic diet formulary across 1,000+ hospitals. Dr. Santos is leading the review. Forza10 Active Line clinical data on food sensitivities could differentiate us vs Hill's and Royal Canin.", priority: "high" },
    { id: 9, name: "Brett Lawson", company: "Chuck & Don's", role: "Assortment Planner", stage: "Qualification", size: "$195K", score: 76, signals: [sig("Midwest premium market growing", "growth"), sig("Clean ingredient mandate", "content"), sig("Looking to replace underperformer", "competitive")], message: "Chuck & Don's replacing an underperforming premium brand across 50 Midwest stores. Brett wants clean-ingredient brands with strong sell-through data. Pull Forza10 velocity reports from similar retailers.", priority: "medium" }
  ],
  "Retail expansion": [
    { id: 10, name: "Laura Chen", company: "Petco Neighborhood", role: "New Store Planner", stage: "Proposal", size: "$340K", score: 82, signals: [sig("60 new neighborhood stores 2026", "growth"), sig("Premium brand priority", "intent"), sig("Planogram reset opportunity", "timing")], message: "Petco opening 60 neighborhood-format stores in 2026. Each store has limited shelf space for only premium brands. Get Natural Code and Forza10 into the planogram template before it locks in May.", priority: "high" },
    { id: 11, name: "Derek Williams", company: "Pet Supermarket", role: "Southeast Regional Buyer", stage: "Discovery", size: "$260K", score: 77, signals: [sig("200 stores in Southeast", "growth"), sig("Premium section expansion", "intent"), sig("Looking for vet-endorsed brands", "content")], message: "Pet Supermarket expanding premium sections in 200 Southeast stores. Derek wants vet-endorsed brands with strong packaging. Forza10 vet line checks both boxes. Schedule a store walk with samples.", priority: "medium" },
    { id: 12, name: "Carla Vasquez", company: "Kroger Pet", role: "Natural Pet Buyer", stage: "Qualification", size: "$410K", score: 80, signals: [sig("Grocery channel pet premium", "growth"), sig("Natural/organic pet food +22%", "momentum"), sig("Shelf space reallocation Q3", "timing")], message: "Kroger reallocating pet aisle space toward natural and premium brands in Q3. Grocery channel is the fastest-growing segment for premium pet food. FirstMate and Natural Code could capture the natural positioning.", priority: "high" },
    { id: 13, name: "Tim Novak", company: "Ren's Pets", role: "Head of Buying", stage: "Negotiation", size: "$185K", score: 84, signals: [sig("Canadian specialty chain", "growth"), sig("FirstMate already listed", "momentum"), sig("Cross-sell opportunity", "intent")], message: "Ren's Pets already carries FirstMate in 40 Canadian stores. Tim is open to adding Forza10 vet line to complement. Cross-sell opportunity worth $185K. Send the Forza10 intro kit this week.", priority: "high" },
    { id: 14, name: "Amy Richardson", company: "Earth Fare", role: "Pet Category Lead", stage: "Discovery", size: "$155K", score: 73, signals: [sig("Natural grocery + pet overlap", "content"), sig("Health-conscious shopper base", "content"), sig("Southeast + Mid-Atlantic footprint", "growth")], message: "Earth Fare is a natural grocery chain whose shoppers over-index on premium pet food. Natural Code's clean-label positioning aligns with their brand. Start with a 6-SKU test in their top 10 stores.", priority: "medium" },
    { id: 15, name: "Jason Park", company: "PetPeople", role: "Franchise Development", stage: "Proposal", size: "$220K", score: 79, signals: [sig("Franchise model scaling fast", "growth"), sig("Curated brand selection", "competitive"), sig("Midwest + East Coast", "growth")], message: "PetPeople franchises expanding rapidly across Midwest and East Coast. Each franchise owner selects from an approved brand list. Get Forza10 on the approved list and it cascades to every new location.", priority: "medium" },
    { id: 16, name: "Nicole Bergman", company: "Healthy Spot", role: "Buyer", stage: "Qualification", size: "$175K", score: 78, signals: [sig("LA premium pet market", "growth"), sig("Wellness-focused concept stores", "content"), sig("Social media driven brand discovery", "content")], message: "Healthy Spot operates wellness-focused pet stores in LA. Their customers discover brands through social media. Propose an influencer collab with Natural Code featuring their high-protein wet food recipes.", priority: "medium" },
    { id: 17, name: "Andrew Kim", company: "Tail Blazers", role: "Purchasing Manager", stage: "Discovery", size: "$140K", score: 72, signals: [sig("Alberta raw + premium chain", "content"), sig("Canadian-made preference", "competitive"), sig("Staff-driven recommendations", "coaching")], message: "Tail Blazers in Alberta focuses on raw and premium nutrition. FirstMate's Canadian production gives us a local advantage. Their staff drives 80% of brand recommendations -- invest in training.", priority: "medium" },
    { id: 18, name: "Michelle Torres", company: "Kahoots Feed & Pet", role: "Regional Buyer", stage: "Qualification", size: "$130K", score: 71, signals: [sig("Southern California + Arizona", "growth"), sig("Farm store + pet hybrid", "content"), sig("Premium pet food underrepresented", "competitive")], message: "Kahoots is a farm-and-pet hybrid store across SoCal and Arizona. Premium pet food is underrepresented in their assortment. Forza10 dry food line could fill the gap with a strong margin story.", priority: "medium" }
  ],
  "Follow-ups": [
    { id: 19, name: "Mike Patterson", company: "Wag N' Wash", role: "Regional Buyer", stage: "Follow-up", size: "$420K", score: 92, signals: [sig("Samples delivered Mar 25", "timing"), sig("Feedback call scheduled Apr 2", "intent"), sig("PO expected if positive", "momentum")], message: "Forza10 samples delivered to Wag N' Wash HQ on March 25. Feedback call scheduled for April 2. Prepare pricing tiers for 12-store intro order and 50-store expansion. Have logistics confirm lead times.", priority: "high" },
    { id: 20, name: "Jessica Huang", company: "Pet Food Express", role: "Category Manager", stage: "Follow-up", size: "$380K", score: 89, signals: [sig("Contract redline received", "intent"), sig("Legal review in progress", "timing"), sig("Launch target May 15", "timing")], message: "Pet Food Express sent contract redline on March 28. Key sticking points: exclusivity window and markdown protection. Get legal review done by April 4 to hit May 15 launch date.", priority: "high" },
    { id: 21, name: "Kevin Tran", company: "Hollywood Feed", role: "Regional Manager", stage: "Follow-up", size: "$290K", score: 85, signals: [sig("Demo events confirmed Apr 10-12", "timing"), sig("Staff training materials needed", "coaching"), sig("PO contingent on demo results", "intent")], message: "Hollywood Feed demo events confirmed for April 10-12 in Nashville, Memphis, and Atlanta. Need staff training materials by April 7. Kevin said PO for 90 stores depends on demo sell-through rates.", priority: "high" },
    { id: 22, name: "Sandra Levine", company: "Unleashed by Petco", role: "Small Format Buyer", stage: "Follow-up", size: "$520K", score: 90, signals: [sig("Planogram submission deadline Apr 15", "timing"), sig("Margin analysis requested", "intent"), sig("Waiting on packaging specs", "risk")], message: "Sandra needs final packaging dimensions and margin analysis by April 15 for planogram submission. If we miss this deadline, we wait 6 months for the next cycle. This is our highest-priority follow-up.", priority: "high" },
    { id: 23, name: "Dr. Alan Reeves", company: "BluePearl Veterinary", role: "Purchasing Director", stage: "Follow-up", size: "$310K", score: 87, signals: [sig("Clinical studies sent Mar 20", "content"), sig("Veterinary board review Apr 8", "timing"), sig("Formulary decision by Apr 30", "timing")], message: "Clinical studies sent to BluePearl on March 20. Their veterinary board reviews on April 8. Formulary decision expected by April 30. Offer to present to the board virtually -- personal touch could tip the decision.", priority: "high" },
    { id: 24, name: "Tim Novak", company: "Ren's Pets", role: "Head of Buying", stage: "Follow-up", size: "$185K", score: 84, signals: [sig("Forza10 samples shipped", "timing"), sig("Cross-sell pricing approved", "momentum"), sig("Training webinar requested", "coaching")], message: "Forza10 samples shipped to Ren's Pets. Tim approved the cross-sell pricing structure. He wants a 30-min training webinar for store managers before launch. Schedule for week of April 14.", priority: "medium" },
    { id: 25, name: "Carla Vasquez", company: "Kroger Pet", role: "Natural Pet Buyer", stage: "Follow-up", size: "$410K", score: 80, signals: [sig("Vendor application submitted", "timing"), sig("Category review meeting May 5", "timing"), sig("Need velocity data from similar retailers", "intent")], message: "Vendor application submitted to Kroger. Category review meeting scheduled May 5. Carla specifically asked for velocity data from comparable grocery-adjacent retailers. Pull POS data from Whole Foods and Sprouts.", priority: "medium" },
    { id: 26, name: "Laura Chen", company: "Petco Neighborhood", role: "New Store Planner", stage: "Follow-up", size: "$340K", score: 82, signals: [sig("Planogram template review Apr 10", "timing"), sig("SKU rationalization needed", "intent"), sig("Must reduce to 12 SKUs max", "risk")], message: "Petco Neighborhood planogram template review is April 10. Laura says max 12 SKUs per brand. Prioritize: 6 Forza10 Active Line (vet differentiation) + 6 Natural Code wet (high margin). Cut anything under $15 retail.", priority: "high" },
    { id: 27, name: "Brett Lawson", company: "Chuck & Don's", role: "Assortment Planner", stage: "Follow-up", size: "$195K", score: 76, signals: [sig("Store visit scheduled Apr 7", "timing"), sig("Competitor performance data requested", "competitive"), sig("Shelf talker samples needed", "content")], message: "Brett wants to see Forza10 in-store at a competitor location. Store visit scheduled April 7 at a local Pet Food Express. Bring shelf talker samples and competitive comparison sheet.", priority: "medium" }
  ],
  "Team coaching": [
    { id: 28, name: "Marcus Johnson", company: "Nasta Pet Food", role: "Territory Rep - Southeast", stage: "Coaching", size: "$1.2M", score: 68, signals: [sig("Pipeline 40% below target", "risk"), sig("Low discovery call volume", "coaching"), sig("Needs vet channel training", "coaching")], message: "Marcus has $1.2M territory but pipeline is 40% below target. Discovery call volume dropped to 8/week (target 15). He struggles with vet channel messaging. Schedule ride-along and vet clinic role-play session.", priority: "high" },
    { id: 29, name: "Ashley Park", company: "Nasta Pet Food", role: "Territory Rep - Pacific NW", stage: "Coaching", size: "$980K", score: 82, signals: [sig("Strong discovery, weak close", "coaching"), sig("Proposal-to-close ratio 22%", "risk"), sig("Needs negotiation framework", "coaching")], message: "Ashley excels at discovery but proposal-to-close ratio is only 22% (team avg 38%). She's leaving money on the table in negotiations. Share the premium value justification framework and do mock negotiations.", priority: "high" },
    { id: 30, name: "Daniel Ortiz", company: "Nasta Pet Food", role: "Territory Rep - Southwest", stage: "Coaching", size: "$1.1M", score: 75, signals: [sig("CRM hygiene issues", "risk"), sig("Forecast accuracy 61%", "coaching"), sig("Deal stages not updated", "coaching")], message: "Daniel's forecast accuracy is 61% (target 85%). He's not updating deal stages in CRM, making pipeline reviews unreliable. Mandate weekly CRM audit and tie it to his quarterly bonus.", priority: "medium" },
    { id: 31, name: "Samantha Reed", company: "Nasta Pet Food", role: "Territory Rep - Midwest", stage: "Coaching", size: "$1.4M", score: 88, signals: [sig("Top performer Q1", "momentum"), sig("Mentor candidate", "coaching"), sig("Ready for key account role", "growth")], message: "Samantha is the top Q1 performer with 112% attainment. She's ready for a key account role. Pair her with Marcus for mentoring and start transitioning her to the Costco or PetSmart relationship.", priority: "medium" },
    { id: 32, name: "Chris Walters", company: "Nasta Pet Food", role: "Territory Rep - Northeast", stage: "Coaching", size: "$1.3M", score: 71, signals: [sig("New hire - 90 day ramp", "coaching"), sig("Product knowledge gaps", "coaching"), sig("Strong retail background", "growth")], message: "Chris joined 60 days ago from a retail management background. Strong relationship skills but gaps in pet nutrition product knowledge. Enroll in Forza10 certification program and pair with Dr. Santos at VCA for ride-along.", priority: "medium" },
    { id: 33, name: "Priya Patel", company: "Nasta Pet Food", role: "Territory Rep - Canada", stage: "Coaching", size: "$890K", score: 79, signals: [sig("FirstMate specialist", "content"), sig("Cross-brand selling opportunity", "coaching"), sig("French language advantage", "growth")], message: "Priya is strong on FirstMate but underperforms on Forza10 and Natural Code. Her French fluency is an asset for Quebec. Train her on the full portfolio and leverage her for the Mondou relationship.", priority: "medium" },
    { id: 34, name: "Jake Morrison", company: "Nasta Pet Food", role: "Territory Rep - Mid-Atlantic", stage: "Coaching", size: "$1.05M", score: 74, signals: [sig("Email response rate low", "risk"), sig("Needs prospecting help", "coaching"), sig("Over-relying on existing accounts", "coaching")], message: "Jake's pipeline is 90% existing accounts with minimal new business. Email response rate is 4% (team avg 11%). Review his outreach templates and implement the pet industry insight-led prospecting approach.", priority: "high" },
    { id: 35, name: "Rachel Kim", company: "Nasta Pet Food", role: "Territory Rep - Online/Ecommerce", stage: "Coaching", size: "$1.6M", score: 85, signals: [sig("Chewy relationship owner", "stakeholder"), sig("Digital marketing savvy", "growth"), sig("Amazon strategy needed", "coaching")], message: "Rachel manages our ecommerce channel including Chewy. She's digitally savvy but needs help building the Amazon Fresh strategy. Connect her with David Kim at Amazon and provide marketplace playbook.", priority: "medium" }
  ]
};

export const CHAT_RESPONSES = {
  top_prospects: "Your hottest prospects this week: (1) Sandra Levine at Unleashed by Petco - $520K, planogram deadline April 15, highest urgency. (2) Mike Patterson at Wag N' Wash - $420K, sample feedback call April 2, 12-store intro order pending. (3) Carla Vasquez at Kroger Pet - $410K, vendor app submitted, category review May 5. (4) Jessica Huang at Pet Food Express - $380K, contract in legal review, May 15 launch target. Total top-4 value: $1.73M. Focus this week on Petco planogram submission and Wag N' Wash feedback call.",
  retail_pipeline: "Retail expansion pipeline: $2.59M across 9 active opportunities. Breakdown by stage: Negotiation $185K (Ren's Pets), Proposal $560K (Petco Neighborhood + PetPeople), Qualification $715K (Kroger + Healthy Spot + Kahoots), Discovery $555K (Pet Supermarket + Earth Fare + Tail Blazers). Grocery channel (Kroger, Earth Fare) is the fastest-growing segment at +22% YoY. Priority: lock Petco Neighborhood planogram by April 15 and prepare Kroger velocity data for May 5 review.",
  this_weeks_priorities: "This week's priority actions: (1) MONDAY: Send packaging specs + margin analysis to Sandra Levine at Petco -- April 15 hard deadline. (2) TUESDAY: Feedback call with Mike Patterson at Wag N' Wash on Forza10 samples. (3) WEDNESDAY: Get legal to finalize Pet Food Express contract redline. (4) THURSDAY: Prepare Hollywood Feed demo materials for April 10-12 events. (5) FRIDAY: Submit Petco Neighborhood SKU rationalization (12 SKUs max). Total revenue at stake this week: $1.95M across these 5 actions.",
  rep_performance: "Team performance Q1 summary: (1) Samantha Reed - Midwest: 112% attainment, $1.57M closed, top performer -- promote to key accounts. (2) Rachel Kim - Ecommerce: 98% attainment, $1.57M, strong Chewy relationship. (3) Priya Patel - Canada: 87% attainment, $774K, FirstMate specialist but needs cross-brand training. (4) Ashley Park - Pacific NW: 81% attainment, $794K, weak closing skills. (5) Daniel Ortiz - Southwest: 76% attainment, $836K, CRM hygiene issues. (6) Jake Morrison - Mid-Atlantic: 72% attainment, $756K, low prospecting. (7) Marcus Johnson - Southeast: 64% attainment, $768K, pipeline gap. (8) Chris Walters - Northeast: ramping (60 days in). Action: ride-along with Marcus, negotiation training for Ashley, CRM audit for Daniel."
};

export const WEEKLY_DATA = [
  { week: "W1 Mar", pipeline: 4.8, closed: 0.42, target: 0.55 },
  { week: "W2 Mar", pipeline: 5.1, closed: 0.61, target: 0.55 },
  { week: "W3 Mar", pipeline: 5.4, closed: 0.38, target: 0.55 },
  { week: "W4 Mar", pipeline: 5.7, closed: 0.72, target: 0.55 },
  { week: "W1 Apr", pipeline: 5.5, closed: 0.49, target: 0.55 },
  { week: "W2 Apr", pipeline: 5.9, closed: 0.53, target: 0.55 }
];

export const PIPELINE_DATA = [
  { stage: "Discovery", value: 1.4, count: 6 },
  { stage: "Qualification", value: 1.2, count: 5 },
  { stage: "Proposal", value: 1.8, count: 5 },
  { stage: "Negotiation", value: 0.9, count: 3 },
  { stage: "Closed Won", value: 2.8, count: 8 }
];

export const CHAT_SUGGESTIONS = [
  "Top prospects",
  "Retail pipeline",
  "This week's priorities",
  "Rep performance"
];

export const FUNNEL_DATA = [
  { stage: "Leads", value: 156 },
  { stage: "Qualified", value: 84 },
  { stage: "Proposal", value: 42 },
  { stage: "Negotiation", value: 19 },
  { stage: "Closed", value: 11 }
];

export const TOP_TEMPLATES = [
  { name: "Retail Buyer Intro Deck", uses: 89, conversion: "32%" },
  { name: "Forza10 Clinical One-Pager", uses: 76, conversion: "37%" },
  { name: "Natural Code Sampling Kit", uses: 64, conversion: "29%" },
  { name: "FirstMate Canadian Story", uses: 52, conversion: "25%" },
  { name: "In-Store Demo Playbook", uses: 48, conversion: "41%" }
];
